[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://your-project-id.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your_supabase_anon_key_here"

[context.deploy-preview.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://your-project-id.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your_supabase_anon_key_here"

[context.branch-deploy.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://your-project-id.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your_supabase_anon_key_here"
